### ISSUE TITLE
libvolk2 in very few distributions

### ISSUE THREAD

**Issue by sm3ulc** [dernasherbrezon/sdr-server#2]
Just comment. Maybe add instructions of how install libvolk2 since it's not included yet.

Fetch latest release:
https://www.libvolk.org/releases.html

Install mako:
sudo apt-get install python3-mako

Normal build procedure:

$ mkdir build
$ cd build
$ cmake ..
$ make
$ make test
$ sudo make install

**Comment by dernasherbrezon** [comment]
I changed instructions to use libvolk1-dev instead of libvolk2-dev. The latter one might not be available on most of platforms. 

Additionally I put a link to their documentation.

I can't add the documentation on how to build volk, because they might change instructions on their end. And my instructions will become obsolete (and misleading).
